name: Patent Update
on:
  schedule:
    - cron: '0 9 * * 4' # Jeden Donnerstag
  workflow_dispatch: # Erlaubt den Button-Trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install python-epo-ops-client
      - name: Run
        env:
          EPO_KEY: ${{ secrets.EPO_KEY }}
          EPO_SECRET: ${{ secrets.EPO_SECRET }}
        run: python epo_app_data.py
      - name: Commit and Push
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@github.com'
          # Falls die Datei neu ist, wird sie hier sicher hinzugefügt
          git add app_patent_data.json || echo "Datei nicht gefunden"
          # Commit nur ausführen, wenn es Änderungen gibt
          git commit -m "Data Update" || echo "Keine Änderungen zum Committen"
          git push || echo "Nichts zum Pushen"
